# Pytorch tutorial
## Basics
Tensors in pytorch. x = num_rows, y=num_columns


In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision        
import torchvision.transforms as transforms
import random

In [2]:
a = str(23)
tens = torch.zeros((2,2,3,1,3))
l = [[1,2,3,4,5],["a","b"],[5,6,7]]
b = "erik"
c = a + b
squeezed = torch.tensor([1,2,3])
unsqueezed = squeezed.unsqueeze(0)
print(squeezed)
print(unsqueezed)

print(c)
print(tens.size(0) + 1)


tensor([ 1,  2,  3])
tensor([[ 1,  2,  3]])
23erik
3


In [3]:
def util_random_tens(tup,seed = 0):   
    class Inner(): 
        no = 2
        def __init__(self,seed):
            self.seed = seed                   
            
        
        def aux_inner(self,tup,no_call=0):            
            if len(tup) == 1:
                Inner.no += 1
                s = no_call            
                random.seed(s+self.seed)
                rand_list = random.sample(range(0,10),tup[0])            
                return rand_list        
            else:
                l = []
                for i in range(tup[0]):
                    Inner.no += 1
                    no_call += 1
                    l.append(Inner.aux_inner(self,tup[1:],no_call=Inner.no))
                return l
            
    
    inner = Inner(seed)
    return inner.aux_inner(tup)
        

ex_tens = torch.tensor(util_random_tens((1,2,5,3,3)))
tensList = [torch.tensor(util_random_tens((5,3,3)))] * 2
print("Tenslist sizes:",tensList[0].size())
print("tenslist:",tensList)
stacked1 = torch.stack(tensList,3)
print("Stacked 1 Size:",stacked1.size())
print("Stacked:",stacked1)
print(ex_tens.size())
print(ex_tens)
split = list(torch.split(ex_tens,int(ex_tens.size(1)/ex_tens.size(1)),dim=1))
print("Split:",split)
stacked = torch.stack(split,5).squeeze()
print("Stacked:",stacked)

print("Stacked size:",stacked.size())
print("ex_tens view:",ex_tens.view(1,45,-1))
print("stacked view:",stacked.view(1,45,-1))
print("Stacked 1 view:",stacked1.view(1,45,-1))
        


Tenslist sizes: torch.Size([5, 3, 3])
tenslist: [tensor([[[ 3,  4,  1],
         [ 9,  1,  7],
         [ 3,  5,  6]],

        [[ 7,  8,  9],
         [ 4,  9,  2],
         [ 3,  0,  8]],

        [[ 2,  1,  7],
         [ 2,  4,  1],
         [ 2,  3,  0]],

        [[ 6,  0,  3],
         [ 7,  4,  8],
         [ 8,  1,  5]],

        [[ 1,  3,  2],
         [ 8,  5,  0],
         [ 5,  0,  8]]]), tensor([[[ 3,  4,  1],
         [ 9,  1,  7],
         [ 3,  5,  6]],

        [[ 7,  8,  9],
         [ 4,  9,  2],
         [ 3,  0,  8]],

        [[ 2,  1,  7],
         [ 2,  4,  1],
         [ 2,  3,  0]],

        [[ 6,  0,  3],
         [ 7,  4,  8],
         [ 8,  1,  5]],

        [[ 1,  3,  2],
         [ 8,  5,  0],
         [ 5,  0,  8]]])]
Stacked 1 Size: torch.Size([5, 3, 3, 2])
Stacked: tensor([[[[ 3,  3],
          [ 4,  4],
          [ 1,  1]],

         [[ 9,  9],
          [ 1,  1],
          [ 7,  7]],

         [[ 3,  3],
          [ 5,  5],
          [ 6,  6]]],


 

In [4]:
mmmult1 = torch.tensor(util_random_tens((3,2,2,1),seed=10))
mmmult2 = torch.tensor(util_random_tens((3,2,3,2)))
print(mmmult1)
print(mmmult2)
print(torch.matmul(mmmult2,mmmult1))
print("-------------------------")
mmmult3 = mmmult1
mmmult4 = mmmult2
print(mmmult3)
print(mmmult4)
print(torch.matmul(mmmult4,mmmult3))




tensor([[[[ 3],
          [ 8]],

         [[ 2],
          [ 2]]],


        [[[ 3],
          [ 1]],

         [[ 0],
          [ 9]]],


        [[[ 9],
          [ 3]],

         [[ 1],
          [ 6]]]])
tensor([[[[ 9,  4],
          [ 5,  2],
          [ 7,  5]],

         [[ 7,  4],
          [ 1,  8],
          [ 5,  7]]],


        [[[ 2,  4],
          [ 2,  3],
          [ 6,  2]],

         [[ 7,  4],
          [ 8,  1],
          [ 0,  7]]],


        [[[ 8,  5],
          [ 9,  1],
          [ 3,  4]],

         [[ 1,  0],
          [ 6,  8],
          [ 1,  6]]]])
tensor([[[[ 59],
          [ 31],
          [ 61]],

         [[ 22],
          [ 18],
          [ 24]]],


        [[[ 10],
          [  9],
          [ 20]],

         [[ 36],
          [  9],
          [ 63]]],


        [[[ 87],
          [ 84],
          [ 39]],

         [[  1],
          [ 54],
          [ 37]]]])
-------------------------
tensor([[[[ 3],
          [ 8]],

         [[ 2],
          [ 2]]

### View tests again ###

In [22]:
orig = torch.tensor(util_random_tens((1,2,3,3,4),seed=10))
print(orig)
orig = orig.view(1,18,4)
print(orig)


tensor([[[[[ 5,  7,  8,  2],
           [ 2,  1,  7,  9],
           [ 2,  4,  1,  6]],

          [[ 4,  1,  0,  9],
           [ 6,  0,  3,  9],
           [ 7,  4,  8,  1]],

          [[ 8,  4,  0,  9],
           [ 1,  3,  2,  7],
           [ 8,  5,  0,  6]]],


         [[[ 6,  9,  1,  0],
           [ 7,  8,  0,  1],
           [ 1,  0,  4,  9]],

          [[ 4,  6,  7,  2],
           [ 5,  1,  6,  4],
           [ 1,  5,  6,  0]],

          [[ 4,  0,  7,  6],
           [ 2,  7,  4,  3],
           [ 8,  0,  7,  5]]]]])
tensor([[[ 5,  7,  8,  2],
         [ 2,  1,  7,  9],
         [ 2,  4,  1,  6],
         [ 4,  1,  0,  9],
         [ 6,  0,  3,  9],
         [ 7,  4,  8,  1],
         [ 8,  4,  0,  9],
         [ 1,  3,  2,  7],
         [ 8,  5,  0,  6],
         [ 6,  9,  1,  0],
         [ 7,  8,  0,  1],
         [ 1,  0,  4,  9],
         [ 4,  6,  7,  2],
         [ 5,  1,  6,  4],
         [ 1,  5,  6,  0],
         [ 4,  0,  7,  6],
         [ 2,  7,  4,  3],
   

In [33]:
orig1 = torch.tensor(util_random_tens((2, 18, 5, 1, 1),seed=10))
print(orig1.squeeze())
orig1 = orig1.squeeze().view(2,2,3,3,5)
#print(orig1)
orig1 = orig1.permute(0,4,1,2,3)
print(orig1)


tensor([[[ 5,  0,  2,  6,  1],
         [ 1,  8,  6,  6,  6],
         [ 8,  3,  2,  0,  4],
         [ 7,  1,  1,  4,  5],
         [ 4,  7,  0,  1,  6],
         [ 5,  6,  2,  9,  2],
         [ 7,  4,  2,  1,  4],
         [ 3,  5,  7,  1,  1],
         [ 7,  9,  5,  7,  7],
         [ 1,  8,  2,  4,  5],
         [ 0,  3,  7,  1,  3],
         [ 5,  9,  0,  1,  6],
         [ 4,  9,  8,  4,  3],
         [ 1,  6,  2,  2,  5],
         [ 9,  8,  0,  4,  9],
         [ 7,  0,  5,  6,  8],
         [ 7,  1,  4,  0,  0],
         [ 4,  7,  2,  8,  9]],

        [[ 2,  2,  4,  3,  7],
         [ 4,  9,  0,  9,  8],
         [ 3,  6,  3,  8,  6],
         [ 1,  0,  1,  8,  4],
         [ 5,  1,  3,  0,  7],
         [ 1,  5,  7,  3,  1],
         [ 7,  1,  1,  2,  7],
         [ 9,  0,  5,  2,  9],
         [ 3,  6,  6,  5,  8],
         [ 3,  5,  0,  1,  5],
         [ 3,  3,  1,  1,  9],
         [ 7,  9,  9,  7,  4],
         [ 4,  7,  2,  7,  6],
         [ 0,  3,  9,  1,  8],
      

Demonstration of dimensions

In [5]:
sh = torch.rand(1,5,3,2)
print(sh)
print("Size:", sh.size())
print(sh[:,:2,0])

tensor([[[[ 0.8730,  0.7601],
          [ 0.4844,  0.1353],
          [ 0.9020,  0.0917]],

         [[ 0.2398,  0.7156],
          [ 0.8463,  0.1376],
          [ 0.0741,  0.5983]],

         [[ 0.7924,  0.9037],
          [ 0.1622,  0.4339],
          [ 0.6485,  0.4512]],

         [[ 0.7584,  0.4324],
          [ 0.2777,  0.1784],
          [ 0.2101,  0.0475]],

         [[ 0.8889,  0.2941],
          [ 0.5548,  0.5109],
          [ 0.5623,  0.9861]]]])
Size: torch.Size([1, 5, 3, 2])
tensor([[[ 0.8730,  0.7601],
         [ 0.2398,  0.7156]]])


In [6]:

o1 = torch.tensor(util_random_tens((2,2), seed=1)) 
o2 = torch.tensor(util_random_tens((2,2), seed=2))
o3 = torch.tensor(util_random_tens((1,3,2,4,1), seed=1))


print(o1)
print(o2)
prod = o1*o2
print(prod)
print((prod.sum(dim=1)))
print("-------------------------")
print(o3)
print(o3.sum(dim=1))
print(o3.sum(dim=1, keepdim= True).size())




tensor([[ 3,  4],
        [ 9,  1]])
tensor([[ 9,  4],
        [ 5,  2]])
tensor([[ 27,  16],
        [ 45,   2]])
tensor([ 43,  47])
-------------------------
tensor([[[[[ 5],
           [ 7],
           [ 7],
           [ 4]],

          [[ 5],
           [ 2],
           [ 2],
           [ 2]]],


         [[[ 3],
           [ 1],
           [ 8],
           [ 1]],

          [[ 8],
           [ 9],
           [ 3],
           [ 6]]],


         [[[ 4],
           [ 5],
           [ 1],
           [ 3]],

          [[ 2],
           [ 8],
           [ 9],
           [ 4]]]]])
tensor([[[[ 12],
          [ 13],
          [ 16],
          [  8]],

         [[ 15],
          [ 19],
          [ 14],
          [ 12]]]])
torch.Size([1, 1, 2, 4, 1])


In [7]:
t1 = torch.tensor(util_random_tens((1,1,2,4,1),seed = 1),dtype=torch.float)
print(t1)
print(t1 ** 2)
print(t1.sum(-2,keepdim=True))
print(t1.size())
print(t1.sum(3,keepdim=True).size())
print(t1.mean(dim=3,keepdim=True))

tensor([[[[[ 5.],
           [ 7.],
           [ 7.],
           [ 4.]],

          [[ 5.],
           [ 2.],
           [ 2.],
           [ 2.]]]]])
tensor([[[[[ 25.],
           [ 49.],
           [ 49.],
           [ 16.]],

          [[ 25.],
           [  4.],
           [  4.],
           [  4.]]]]])
tensor([[[[[ 23.]],

          [[ 11.]]]]])
torch.Size([1, 1, 2, 4, 1])
torch.Size([1, 1, 2, 1, 1])
tensor([[[[[ 5.7500]],

          [[ 2.7500]]]]])


In [8]:
pred = torch.tensor(util_random_tens((1,2,2,4,1)),dtype=torch.float)
pred1 = torch.tensor(util_random_tens((1,2,2,4,1),seed=3),dtype=torch.float)

print(pred1)
print(pred.transpose(3,4))
print(torch.matmul(pred.transpose(3,4),pred1))


tensor([[[[[ 7.],
           [ 7.],
           [ 4.],
           [ 3.]],

          [[ 2.],
           [ 2.],
           [ 2.],
           [ 6.]]],


         [[[ 1.],
           [ 8.],
           [ 1.],
           [ 8.]],

          [[ 9.],
           [ 3.],
           [ 6.],
           [ 0.]]]]])
tensor([[[[[ 9.,  3.,  9.,  7.]],

          [[ 3.,  8.,  0.,  2.]]],


         [[[ 6.,  7.,  8.,  0.]],

          [[ 8.,  5.,  6.,  7.]]]]])
tensor([[[[[ 141.]],

          [[  34.]]],


         [[[  70.]],

          [[ 123.]]]]])


In [9]:
mm1 = torch.tensor(util_random_tens((2,1),seed=1))
mm2 = torch.tensor(util_random_tens((2,1),seed=2))
print(mm1)
print(mm2)
print(mm2.transpose(0,1))
print(torch.matmul(mm2.transpose(0,1),mm1))

tensor([[ 3],
        [ 9]])
tensor([[ 9],
        [ 5]])
tensor([[ 9,  5]])
tensor([[ 72]])


In [10]:
x = torch.rand(5,3)
zeros = torch.zeros(3,5,dtype = torch.long)
print(x)
print(zeros)
print(torch.max(x))

tensor([[ 0.9741,  0.7608,  0.5925],
        [ 0.8617,  0.0878,  0.7443],
        [ 0.2006,  0.5017,  0.3289],
        [ 0.2443,  0.2873,  0.1214],
        [ 0.6605,  0.3113,  0.1299]])
tensor([[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]])
tensor(0.9741)


Initializing tensors directly from data and priting its size


In [11]:
data = [[1,2,3],[4,5,6]]
data_t = torch.tensor(data)
print(data_t)
print(data_t.size() == torch.Size([2,3]))
print(9-data_t)
print()

tensor([[ 1,  2,  3],
        [ 4,  5,  6]])
True
tensor([[ 8,  7,  6],
        [ 5,  4,  3]])



### Eye ###

In [12]:
eye = torch.eye(3)
print(eye)
print(eye[:,:,None])


tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])
tensor([[[ 1.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 1.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 1.]]])


### Arithmetic operations

In [13]:
x = torch.tensor([[1,2,3],[10,11,13]])
y = torch.tensor([[5,6,7],[20,21,22]])
trans = torch.tensor([[[5,6,7],[20,21,22]]])
trans1 = torch.tensor([[1,2,3],[10,11,13]])
mm1 = torch.tensor([[1,2],[4,3]]).double()
mm2 = torch.tensor([[2,3]]).double()
mmmult1 = torch.tensor(rand)
mmmm = torch.matmul(mm2,mm1)
print("Resutl of matrix multiply 1: \n",mmmm)


print("Normal multiply:\n")
print(mm1*mm2)

print("Square root and sum: \n")
z = torch.sqrt(mm1**2).sum(-2)
print(z)

print("Two different transposes")
print("Original dim: {}".format(trans.size()))
print(trans.transpose(0,1))
print(trans.transpose(0,1).size())
print(trans.transpose(2,0))
print(trans.transpose(2,0).size())
print("trans1.t()")
print(trans1.t())
print("\n\n")

print("Matrix multiply:")
print(x.mm(y.transpose(0,1)))

print("Addition normal")
print(x+y)

print("Addition with pytorch function")
print(torch.add(x,y))

print("Addition with providing output tensor")
result = torch.zeros(2,3, dtype = torch.long)
torch.add(x,y,out=result)
print(result)

print("Addition in place (x is changed in this example)")
x.add_(y)
print(x)


NameError: name 'rand' is not defined

__NOTE:__ Operations that mutate a tensor in place are post ficed with "_"

### Addressing elements in tensor

In [ ]:
rn = torch.rand(7,4)
print(rn)
print("Column 0")
print(rn[:,0])
print("Row 0")
print(rn[0,:])
print("Second and third row and second and third column")
print(rn[1:3,1:3])

### Resizing torch tensors

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
v = x.view(1,-1)
print(x.size(),"\n",x)
print(y.size(),"\n",y)
print(z.size(),"\n",z)
print(v.size(),"\n",v)


## Stacking Tensors ##

In [ ]:
d = torch.rand(2,3,4)
print(d)
stacked = torch.stack([d] * 2,dim=2).unsqueeze(4)
print(stacked)

In [ ]:
stack1 = tens = torch.tensor([[[[1,2],[3,4]]],[[[5,6],[7,8]]],[[[9,10],[11,12]]]])
stack2 = tens = torch.tensor([[[[11,22],[33,44]]],[[[1,2],[3,4]]],[[[1,2],[3,4]]]])
ls = [stack1, stack2]
print("Tensor 1:")
print(stack1)
print("Tensor 2:")
print(stack2)
print("------------------")
print("Stacked tensors:")
stacked = torch.stack(ls,1) 
print(stacked)
print("Tensor sizes:",stack1.size())
print("Stacked sizes:",stacked.size())

## Some Soft Max understanding ##

In [ ]:
te1 = torch.zeros([2,3,1])
te2 = torch.zeros([2,2])
exmpl1 = torch.tensor([[[1],[2]],[[3],[4]]],dtype=torch.float)
exml2 = torch.tensor([1,2,3,4], dtype=torch.float)
print(te1)
softmax = F.softmax(exmpl1,dim = 0)
sm2 = F.softmax(exml2,dim=0)
print(softmax)
print(sm2)

### Squashing function ###

In [ ]:
tens = torch.tensor([[[1,2,3],[2,1,3],[2,1,3]],[[10,20,30],[20,10,30],[20,10,30]]]).double()
print(tens.size())
CapsSquareNorm = tens.sum(1,keepdim=True)
CapsSum = torch.sqrt(CapsSquareNorm)
CapsOut = CapsSquareNorm*tens/(1+CapsSquareNorm*CapsSum)

print(CapsSquareNorm)
print(CapsSum)
print(CapsOut)

## Matrix multiplications (in batch learning) ##
Input data has dimensions `[batch,in,hidden,out]`. Lets say is 1 hidden layer 

In [ ]:
data = torch.rand(3,2).double()
print(data)
weight_matrix1 = torch.tensor([[2,2,2],[5,5,5]]).double()
print(weight_matrix1)
weight_matrix2 = torch.tensor([[2,2,2,2,2],[5,5,5,5,5],[10,10,10,10,10]]).double()
print(weight_matrix2)
prod1 = data.mm(weight_matrix1)
prod2 = prod1.mm(weight_matrix2)
print("\n\nResult of FIRST multiplication:")
print(prod1)
print("\n\nResult of SECOND multiplication:")
print(prod2)

## Autograd and gradients

In [ ]:
x1 = torch.ones(2, 3, requires_grad=True)
print(x1)

Doing an operation on a tensor:

In [ ]:
y1 = x1 + 2
print(y1)
print(y1.grad_fn)

y is a result of a function thus it has a __.grad_fn__ attribute which specifies the which function it is result of.

In [ ]:
z1 = y1 * y1 * 3
out = z1.mean()

print(z1)
print(z1.grad_fn)
print(out)

Geting gradients of __out__ :

In [ ]:
out.backward(retain_graph = False)
print(x1.grad)

In [ ]:
x2 = torch.randn(3,requires_grad=True)
print(x2)

y2 = x2 * 2
while y2.data.norm() < 1000:
    y2 = y2 * 2

print(y2)

In [ ]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y2.backward(gradients)

print(x2.grad)

__Example from CS231n__

In [ ]:
a1 = torch.tensor(2,requires_grad=True,dtype=torch.float64)
b1 = torch.tensor(-1,requires_grad=True,dtype=torch.float64)
a2 = torch.tensor(-3,requires_grad=True,dtype=torch.float64)
b2 = torch.tensor(-2,requires_grad=True,dtype=torch.float64)
c1 = torch.tensor(-3,requires_grad=True,dtype=torch.float64)

prod1 = a1 * b1
prod2 = a2 * b2
print(prod1)
print(prod2)

sum1 = prod1 + prod2
print(sum1)

sum2 = sum1 + c1

print(sum2)
sum2 = sum2 * (-1)
print(sum2)
sum2 = torch.exp(sum2.double())
print(sum2)
sum2 = sum2 + 1
print(sum2)
sum2 = 1/sum2
print(sum2)
print("Gradients:")
grads = torch.tensor([1,0.1],dtype=torch.double)
sum2.backward(grads)


print(a1.grad)
print(b1.grad)
print(a2.grad)
print(b2.grad)
print(c1.grad)





## Networks


In [ ]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

__Learnable parameters of the network :__

In [ ]:
params = list(net.parameters())
for i in params:
    print(i.size())
print(len(params))
print(params[0].size())

__Inputing a random 32x32 tensor__

In [ ]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

torch.nn only supports mini-batches. The entire torch.nn package only supports inputs that are a mini-batch of samples, and not a single sample.

For example, nn.Conv2d will take in a 4D Tensor of nSamples x nChannels x Height x Width.

If you have a single sample, just use input.unsqueeze(0) to add a fake batch dimension

__Computing the loss function__

In [ ]:

target = torch.arange(1, 11)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(out, target)
print(loss)
print(loss.grad_fn)

In [ ]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

__BAckpropagation of the error__

In [ ]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

In [ ]:
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update

## CIFAR-10 classifier example

The output of torchvision datasets are PILImage images of range [0, 1]. We transform them to Tensors of normalized range [-1, 1].

In [ ]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

__SHOWING SOME IMAGES__

In [ ]:
def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))


# get some random training images
dataiter = iter(trainloader)
images, labels = dataiter.next()

# show images
imshow(torchvision.utils.make_grid(images))
# print labels
print(' '.join('%5s' % classes[labels[j]] for j in range(4)))

__DEFINE THE NETWORK__

In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()

__DEFINE LOSS AND OPTIMIZER__

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

__TRAIN THE NETWORK__

In [ ]:
for epoch in range(3):  # loop over the dataset 3 times

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # get the inputs
        inputs, labels = data

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')

__TESTING AGAINST TRAINING DATA__

In [ ]:
correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = net(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print('Accuracy of the network on the 10000 test images: %d %%' % (
    100 * correct / total))

In [ ]:
class_correct = list(0. for i in range(10))
class_total = list(0. for i in range(10))
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = net(images)
        _, predicted = torch.max(outputs, 1)
        c = (predicted == labels).squeeze()
        for i in range(4):
            label = labels[i]
            class_correct[label] += c[i].item()
            class_total[label] += 1


for i in range(10):
    print('Accuracy of %5s : %2d %%' % (
        classes[i], 100 * class_correct[i] / class_total[i]))