In [9]:
from itertools import islice
import numpy as np

a = list(range(10))

print(list(islice(a,3,None,2)))



a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,21,31],[41,51,61],[71,81,91]]])
print(a.shape)
a = a.reshape(3,2,-1)
print(a)


[3, 5, 7, 9]
(2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 21 31]]

 [[41 51 61]
  [71 81 91]]]
