In [6]:
from itertools import islice
import numpy as np



a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,21,31],[41,51,61],[71,81,91]]])
print(a.shape)
print(a)
print("------------")
print(a.reshape(3,2,-1))
print("------------")
print(a.swapaxes(0,1))


(2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 21 31]
  [41 51 61]
  [71 81 91]]]
------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 21 31]]

 [[41 51 61]
  [71 81 91]]]
------------
[[[ 1  2  3]
  [11 21 31]]

 [[ 4  5  6]
  [41 51 61]]

 [[ 7  8  9]
  [71 81 91]]]
